// <auto-generated />
using System;
using BinggoWallpapers.Core.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinggoWallpapers.Core.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("BINARY")
                .HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BinggoWallpapers.Core.DataAccess.Domains.WallpaperEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActualDate")
                        .HasColumnType("DATE");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActualDate")
                        .HasDatabaseName("IX_Wallpapers_ActualDate");

                    b.HasIndex("MarketCode")
                        .HasDatabaseName("IX_Wallpapers_MarketCode");

                    b.HasIndex("ResolutionCode")
                        .HasDatabaseName("IX_Wallpapers_ResolutionCode");

                    b.HasIndex("MarketCode", "ResolutionCode", "Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_Wallpapers_MarketCode_ResolutionCode_Hash");

                    b.ToTable("wallpapers", "gallery");
                });
#pragma warning restore 612, 618
        }
    }
}
